"use client";

import { FormEvent, useEffect, useState } from "react";

export default function AdminSettingsPage() {
  const [settings, setSettings] = useState({ whatsappNumber: "", activeDesign: "design1", siteName: "" });
  const [message, setMessage] = useState("");
  useEffect(() => { void fetch("/api/admin/settings").then((response) => response.json()).then((payload: { data?: { whatsappNumber?: string | null; activeDesign?: string; siteSettings?: { siteName?: string } } }) => { if (payload.data) setSettings({ whatsappNumber: payload.data.whatsappNumber ?? "", activeDesign: payload.data.activeDesign ?? "design1", siteName: payload.data.siteSettings?.siteName ?? "" }); }); }, []);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch("/api/admin/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ whatsappNumber: settings.whatsappNumber, activeDesign: settings.activeDesign, siteSettings: { siteName: settings.siteName } }) }); setMessage(response.ok ? "Settings saved." : "Unable to save settings."); }
  return <div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-700">Configuration</p><h1 className="mt-2 text-3xl font-semibold">Catalog settings</h1><form onSubmit={save} className="mt-8 max-w-2xl rounded-xl border border-slate-200 bg-white p-6"><div className="grid gap-5"><label className="text-sm font-medium">WhatsApp number<input value={settings.whatsappNumber} onChange={(event) => setSettings({ ...settings, whatsappNumber: event.target.value })} placeholder="+123..." className="mt-1 w-full rounded border px-3 py-2 font-normal" /></label><label className="text-sm font-medium">Active catalog design<select value={settings.activeDesign} onChange={(event) => setSettings({ ...settings, activeDesign: event.target.value })} className="mt-1 w-full rounded border px-3 py-2 font-normal"><option value="design1">Design 1</option><option value="design2">Design 2</option></select></label><label className="text-sm font-medium">Site name<input value={settings.siteName} onChange={(event) => setSettings({ ...settings, siteName: event.target.value })} className="mt-1 w-full rounded border px-3 py-2 font-normal" /></label></div>{message ? <p className="mt-4 text-sm text-slate-600">{message}</p> : null}<button className="mt-6 rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Save settings</button></form></div>;
}