"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Product = { id: string; name: string; sku: string | null; description: string | null; price: string | number | null; stock: number | null; status: boolean; images: unknown; variants: unknown; category: { name: string; slug: string } | null };

function imageUrl(images: unknown) { return Array.isArray(images) && typeof images[0] === "string" ? images[0] : null; }
function money(value: Product["price"]) { return value === null || value === undefined ? "Price on request" : `AED ${Number(value).toLocaleString(undefined, { minimumFractionDigits: 2 })}`; }

export function ProductDetail({ id }: { id: string }) {
  const [product, setProduct] = useState<Product | null>(null);
  const [related, setRelated] = useState<Product[]>([]);
  const [whatsappNumber, setWhatsappNumber] = useState<string | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { const timer = window.setTimeout(() => { void Promise.all([fetch(`/api/products/${id}`), fetch(`/api/products/${id}/related`), fetch("/api/config")]).then(async ([detailResponse, relatedResponse, configResponse]) => { const detail = await detailResponse.json() as { data?: Product; error?: string }; const relatedPayload = await relatedResponse.json() as { data?: Product[] }; const configPayload = await configResponse.json() as { data?: { whatsappNumber?: string | null } }; if (!detailResponse.ok) throw new Error(detail.error ?? "Product not found"); setProduct(detail.data ?? null); setRelated(relatedPayload.data ?? []); setWhatsappNumber(configPayload.data?.whatsappNumber ?? null); }).catch((loadError) => setError(loadError instanceof Error ? loadError.message : "Unable to load product")); }, 0); return () => window.clearTimeout(timer); }, [id]);
  if (error) return <main className="min-h-screen bg-slate-50 p-8 text-center"><p className="text-rose-600">{error}</p><Link href="/" className="mt-4 inline-block underline">Back to catalog</Link></main>;
  if (!product) return <main className="min-h-screen bg-slate-50 p-8"><div className="mx-auto h-96 max-w-6xl animate-pulse rounded-3xl bg-slate-200" /></main>;
  const image = imageUrl(product.images); const whatsapp = whatsappNumber && product.status && product.stock && product.stock > 0 ? `https://wa.me/${whatsappNumber.replace(/\D/g, "")}?text=${encodeURIComponent(`Hello, I am interested in ${product.name}${product.sku ? ` (${product.sku})` : ""}.`)}` : null;
  return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white px-5 py-5"><div className="mx-auto flex max-w-6xl justify-between"><Link href="/" className="font-semibold">Quick Shelf</Link><Link href="/" className="text-sm text-slate-500">Back to catalog</Link></div></header><div className="mx-auto max-w-6xl px-5 py-10"><div className="grid gap-10 lg:grid-cols-2"><div className="aspect-square rounded-3xl bg-slate-100" style={image ? { backgroundImage: `url(${image})`, backgroundPosition: "center", backgroundSize: "cover" } : undefined}>{!image ? <div className="grid h-full place-items-center text-slate-400">No image available</div> : null}</div><div className="self-center"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-700">{product.category?.name ?? "Catalog"}</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">{product.name}</h1><p className="mt-5 text-2xl font-semibold">{money(product.price)}</p><p className={`mt-2 text-sm ${product.stock && product.stock > 0 ? "text-emerald-700" : "text-rose-600"}`}>{product.stock && product.stock > 0 ? `${product.stock} available` : "Out of stock"}</p>{product.sku ? <p className="mt-5 text-sm text-slate-500">SKU: {product.sku}</p> : null}<p className="mt-6 whitespace-pre-line leading-7 text-slate-600">{product.description ?? "Details coming soon."}</p>{whatsapp ? <a href={whatsapp} target="_blank" rel="noreferrer" className="mt-8 inline-flex rounded-full bg-emerald-500 px-5 py-3 text-sm font-semibold text-white">Enquire on WhatsApp</a> : null}</div></div>{related.length ? <section className="mt-16"><h2 className="text-2xl font-semibold">You may also like</h2><div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-4">{related.map((item) => <Link key={item.id} href={`/products/${item.id}`} className="rounded-2xl bg-white p-4 shadow-sm"><div className="aspect-square rounded-xl bg-slate-100" style={imageUrl(item.images) ? { backgroundImage: `url(${imageUrl(item.images)})`, backgroundPosition: "center", backgroundSize: "cover" } : undefined} /><p className="mt-3 line-clamp-2 text-sm font-semibold">{item.name}</p><p className="mt-1 text-sm text-slate-500">{money(item.price)}</p></Link>)}</div></section> : null}</div></main>;
}